export const CuisineRoute = [
  {
    id: 1,
    title: "Martabak",
    route: "/martabak",
    img: "/CuisinePng/martabak.jpg",
  },
  {
    id: 2,
    title: "Bako & soto",
    route: "/bako",
    img: "/CuisinePng/bako.jpg",
  },
  {
    id: 3,
    title: "Bakery",
    route: "/bakery",
    img: "/CuisinePng/bakery.jpg",
  },
  {
    id: 4,
    title: "Chinese",
    route: "/chinese",
    img: "/CuisinePng/chinese.jpg",
  },
  {
    id: 5,
    title: "Western",
    route: "/western",
    img: "/CuisinePng/western.jpg",
  },
  {
    id: 6,
    title: "Middle Eastern",
    route: "/middle-east",
    img: "/CuisinePng/eastern.jpg",
  },
  {
    id: 7,
    title: "Fast Food",
    route: "/fast-food",
    img: "/CuisinePng/fastfood.jpg",
  },
  {
    id: 8,
    title: "Japanese",
    route: "/japanese",
    img: "/CuisinePng/japanese.jpg",
  },
  {
    id: 9,
    title: "Snacks",
    route: "/snacks",
    img: "/CuisinePng/snacks.jpg",
  },
  {
    id: 10,
    title: "Sate",
    route: "/sate",
    img: "/CuisinePng/Sate.jpg",
  },
  {
    id: 11,
    title: "Pizza & pasta",
    route: "/pizza",
    img: "/CuisinePng/pizza.jpg",
  },
  {
    id: 12,
    title: "Noodles",
    route: "/noodles",
    img: "/CuisinePng/noodles.jpg",
  },
  {
    id: 13,
    title: "Beverages",
    route: "/beverages",
    img: "/CuisinePng/beverages.jpg",
  },
  {
    id: 14,
    title: "Korean",
    route: "/korean",
    img: "/CuisinePng/korean.jpg",
  },
  {
    id: 15,
    title: "Seafood",
    route: "/seafood",
    img: "/CuisinePng/seafood.jpg",
  },
  {
    id: 16,
    title: "Coffee",
    route: "/coffee",
    img: "/CuisinePng/coffee.jpg",
  },
];
