export const DataFiles = [
  {
    id: 1,
    foodCategory: "rice",
    foodName: "Chicken Fried Rice",
    price: "3.21",
    randomValue1: "3.35",
    randomValue2: 2,
    location: "Texas",
    image: "https://i.ibb.co/F0Gwywd/rachel-park-hrlvr2-Zl-UNk-unsplash.jpg",
  },
  {
    id: 2,
    foodCategory: "chocolates",
    foodName: "Dark Chocolate Truffle",
    price: "4.52",
    randomValue1: "2.78",
    randomValue2: 5,
    location: "Canada",
    image:
      "https://i.ibb.co/X2kj9VV/slashio-photography-Ws-Mo-Ae-XHjc-M-unsplash.jpg",
  },
  {
    id: 3,
    foodCategory: "cheese",
    foodName: "Four Cheese Pizza",
    price: "3.76",
    randomValue1: "1.56",
    randomValue2: 4,
    location: "Pittsburgh",
    image:
      "https://i.ibb.co/Kbj1fjX/side-view-pilaf-with-stewed-beef-meat-plate.jpg",
  },
  {
    id: 4,
    foodCategory: "rice",
    foodName: "Vegetable Biryani",
    price: "2.57",
    randomValue1: "0.71",
    randomValue2: 5,
    location: "New York",
    image: "https://i.ibb.co/2v09d6T/pic12.jpg",
  },
  {
    id: 5,
    foodCategory: "chocolates",
    foodName: "Milk Chocolate Bar",
    price: "1.35",
    randomValue1: "1.24",
    randomValue2: 1,
    location: "Atlanta",
    image: "https://i.ibb.co/2NChpqC/pic11.jpg",
  },
  {
    id: 6,
    foodCategory: "rice",
    foodName: "Sushi Platter",
    price: "4.82",
    randomValue1: "3.08",
    randomValue2: 3,
    location: "Los Angeles",
    image: "https://i.ibb.co/C089ctL/pic10.jpg",
  },
  {
    id: 7,
    foodCategory: "cheese",
    foodName: "Cheese Fondue",
    price: "3.44",
    randomValue1: "4.42",
    randomValue2: 3,
    location: "Texas",
    image: "https://i.ibb.co/mBxvRx9/pic4.jpg",
  },
  {
    id: 8,
    foodCategory: "chocolates",
    foodName: "Chocolate Chip Cookies",
    price: "1.65",
    randomValue1: "3.48",
    randomValue2: 4,
    location: "Canada",
    image: "https://i.ibb.co/fD43jRL/offer-image-2.jpg",
  },
  {
    id: 9,
    foodCategory: "rice",
    foodName: "Paella",
    price: "2.72",
    randomValue1: "4.39",
    randomValue2: 4,
    location: "Pittsburgh",
    image: "https://i.ibb.co/pJffQz4/offer-image-1.jpg",
  },
  {
    id: 10,
    foodCategory: "cheese",
    foodName: "Mozzarella Caprese",
    price: "4.14",
    randomValue1: "1.71",
    randomValue2: 2,
    location: "New York",
    image:
      "https://i.ibb.co/k370cbt/megan-bucknall-edy-Yn-Pwpc-XQ-unsplash.jpg",
  },
  {
    id: 11,
    foodCategory: "rice",
    foodName: "Jambalaya",
    price: "1.98",
    randomValue1: "1.96",
    randomValue2: 1,
    location: "Atlanta",
    image: "https://i.ibb.co/Z6wCfcV/nicholas-grande-d9jc-PTRD9fo-unsplash.jpg",
  },
  {
    id: 12,
    foodCategory: "chocolates",
    foodName: "Chocolate Mousse",
    price: "3.87",
    randomValue1: "4.58",
    randomValue2: 5,
    location: "Los Angeles",
    image: "https://i.ibb.co/f09gGS2/max-griss-c-To-NEm70cv-E-unsplash.jpg",
  },
  {
    id: 13,
    foodCategory: "cheese",
    foodName: "Grilled Cheese Sandwich",
    price: "2.31",
    randomValue1: "2.62",
    randomValue2: 3,
    location: "Texas",
    image: "https://i.ibb.co/D7tnB68/mae-mu-Pvclb-i-HHYY-unsplash-1.jpg",
  },
  {
    id: 14,
    foodCategory: "rice",
    foodName: "Bibimbap",
    price: "4.35",
    randomValue1: "0.56",
    randomValue2: 5,
    location: "Canada",
    image:
      "https://i.ibb.co/DKGQC2M/karolina-kolodziejczak-Mzh95z-Pm-OIM-unsplash.jpg",
  },
  {
    id: 15,
    foodCategory: "chocolates",
    foodName: "Chocolate Covered Strawberries",
    price: "4.25",
    randomValue1: "1.64",
    randomValue2: 1,
    location: "Pittsburgh",
    image: "https://i.ibb.co/M8rtbm2/keto-hero.jpg",
  },
  {
    id: 16,
    foodCategory: "rice",
    foodName: "Sushi Burrito",
    price: "2.63",
    randomValue1: "3.42",
    randomValue2: 4,
    location: "New York",
    image: "https://i.ibb.co/09k2DBz/jenn-kosar-k5-VGs9q-Qubc-unsplash.jpg",
  },
  {
    id: 17,
    foodCategory: "cheese",
    foodName: "Macaroni and Cheese",
    price: "4.57",
    randomValue1: "2.53",
    randomValue2: 2,
    location: "Atlanta",
    image: "https://i.ibb.co/dmLhYmb/jimmy-dean-Yn0l7uw-Brpw-unsplash.jpg",
  },
  {
    id: 18,
    foodCategory: "chocolates",
    foodName: "White Chocolate Raspberry Cake",
    price: "1.85",
    randomValue1: "3.86",
    randomValue2: 4,
    location: "Los Angeles",
    image: "https://i.ibb.co/x8rm5MN/julia-kicova-K-Jg-Wm-P-82k-unsplash.jpg",
  },
  {
    id: 19,
    foodCategory: "rice",
    foodName: "Stir-Fried Noodles",
    price: "4.01",
    randomValue1: "1.27",
    randomValue2: 5,
    location: "Texas",
    image: "https://i.ibb.co/NrCRjhp/img11.jpg",
  },
  {
    id: 20,
    foodCategory: "cheese",
    foodName: "Cheeseburger",
    price: "3.04",
    randomValue1: "2.79",
    randomValue2: 3,
    location: "Canada",
    image: "https://i.ibb.co/M8QB2FK/img8.jpg",
  },
  {
    id: 21,
    foodCategory: "rice",
    foodName: "Saffron Rice",
    price: "1.21",
    randomValue1: "4.42",
    randomValue2: 3,
    location: "Pittsburgh",
    image: "https://i.ibb.co/vZTBr4H/img10.jpg",
  },
  {
    id: 22,
    foodCategory: "chocolates",
    foodName: "Chocolate Lava Cake",
    price: "2.29",
    randomValue1: "3.82",
    randomValue2: 4,
    location: "New York",
    image: "https://i.ibb.co/yQbmyf0/eve-maier-f979oad8-TDs-unsplash.jpg",
  },
  {
    id: 23,
    foodCategory: "cheese",
    foodName: "Cheese Platter",
    price: "3.57",
    randomValue1: "0.75",
    randomValue2: 1,
    location: "Atlanta",
    image:
      "https://i.ibb.co/pWnL65y/anna-tukhfatullina-food-photographer-stylist-Mzy-Ojt-CI70-unsplash.jpg",
  },
  {
    id: 24,
    foodCategory: "rice",
    foodName: "Pilaf",
    price: "1.65",
    randomValue1: "2.98",
    randomValue2: 2,
    location: "Los Angeles",
    image:
      "https://i.ibb.co/wLq1sL5/fried-rice-with-minced-pork-tomato-carrot-cucumber-plate.jpg",
  },
  {
    id: 25,
    foodCategory: "chocolates",
    foodName: "Chocolate Milkshake",
    price: "4.64",
    randomValue1: "1.29",
    randomValue2: 3,
    location: "Texas",
    image: "https://i.ibb.co/kcyFfYG/airam-dato-on-DYVVuq3-J-Zg-unsplash.jpg",
  },
  {
    id: 26,
    foodCategory: "rice",
    foodName: "Teriyaki Chicken Bowl",
    price: "3.18",
    randomValue1: "3.77",
    randomValue2: 4,
    location: "Canada",
    image: "https://i.ibb.co/C8mVj5M/homescreenify-s-A3wym-Yqya-I-unsplash.jpg",
  },
  {
    id: 27,
    foodCategory: "cheese",
    foodName: "Cheese Stuffed Mushrooms",
    price: "2.44",
    randomValue1: "2.56",
    randomValue2: 5,
    location: "Pittsburgh",
    image: "https://i.ibb.co/B3nJth7/dan-gold-4-jh-DO54-BYg-unsplash.jpg",
  },
  {
    id: 28,
    foodCategory: "chocolates",
    foodName: "Chocolate Pudding",
    price: "3.29",
    randomValue1: "1.91",
    randomValue2: 1,
    location: "New York",
    image:
      "https://i.ibb.co/J5DGr5n/ambitious-creative-co-rick-barrett-i2b-Ucr-KZB-U-unsplash.jpg",
  },
  {
    id: 29,
    foodCategory: "rice",
    foodName: "Risotto",
    price: "4.78",
    randomValue1: "0.94",
    randomValue2: 2,
    location: "Atlanta",
    image: "https://i.ibb.co/GtPRxJq/ben-lei-fl-Fd8-L7-B3g-unsplash.jpg",
  },
  {
    id: 30,
    foodCategory: "cheese",
    foodName: "Cheese and Pepperoni Pizza",
    price: "2.95",
    randomValue1: "4.29",
    randomValue2: 3,
    location: "Los Angeles",
    image: "https://i.ibb.co/TWFtq2Q/dan-gold-E6-Hj-Qa-B7-UEA-unsplash.jpg",
  },
  {
    id: 31,
    foodCategory: "rice",
    foodName: "Fried Rice with Shrimp",
    price: "1.78",
    randomValue1: "3.84",
    randomValue2: 4,
    location: "Texas",
    image: "https://i.ibb.co/7CJyKdY/emanuel-ekstrom-KJOUns-GXq58-unsplash.jpg",
  },
  {
    id: 32,
    foodCategory: "chocolates",
    foodName: "Chocolate Chip Pancakes",
    price: "4.33",
    randomValue1: "1.56",
    randomValue2: 1,
    location: "Canada",
    image: "https://i.ibb.co/Fqqt233/pic8.jpg",
  },
  {
    id: 33,
    foodCategory: "cheese",
    foodName: "Grilled Cheese and Tomato Soup",
    price: "3.12",
    randomValue1: "3.01",
    randomValue2: 5,
    location: "Pittsburgh",
    image: "https://i.ibb.co/R0pRGDp/tyler-nix-EVx2e-SGd71s-unsplash.jpg",
  },
];
