export const LocationDb = [
  {
    id: 1,
    state: "Pennsylvania",
    state_abrev: "PA",
    city: "Erie",
    street: "Little Fleur",
    street_number: "170",
  },
  {
    id: 2,
    state: "Michigan",
    state_abrev: "MI",
    city: "Lansing",
    street: "Ridge Oak",
    street_number: "99",
  },
  {
    id: 3,
    state: "Los Angeles",
    state_abrev: "LA",
    city: "Phoenix",
    street: "Manley",
    street_number: "005",
  },
  {
    id: 4,
    state: "New York",
    state_abrev: "NY",
    city: "Brooklyn",
    street: "Nelson",
    street_number: "87369",
  },
  {
    id: 5,
    state: "South Carolina",
    state_abrev: "SC",
    city: "Columbia",
    street: "Brentwood",
    street_number: "84",
  },
  {
    id: 6,
    state: "Los Angeles",
    state_abrev: "LA",
    city: "Boise",
    street: "Lindbergh",
    street_number: "16",
  },
  {
    id: 7,
    state: "Florida",
    state_abrev: "FL",
    city: "PompanoBeach",
    street: "Fieldstone",
    street_number: "591",
  },
  {
    id: 8,
    state: "Texas",
    state_abrev: "TX",
    city: "San Antonio",
    street: "Dawn",
    street_number: "47",
  },
  {
    id: 9,
    state: "Los Angeles",
    state_abrev: "LA",
    city: "Olympia",
    street: "Huxley",
    street_number: "7",
  },
  {
    id: 10,
    state: "Nevada",
    state_abrev: "NV",
    city: "CarsonCity",
    street: "Kings",
    street_number: "44462",
  },
  {
    id: 11,
    state: "Atlanta",
    state_abrev: "GA",
    city: "Herndon",
    street: "Walton",
    street_number: "651",
  },
  {
    id: 12,
    state: "Texas",
    state_abrev: "TX",
    city: "ElPaso",
    street: "Fair Oaks",
    street_number: "44",
  },
  {
    id: 13,
    state: "Los Angeles",
    state_abrev: "LA",
    city: "El Paso",
    street: "Pankratz",
    street_number: "640",
  },
  {
    id: 14,
    state: "Atlanta",
    state_abrev: "GA",
    city: "Tacoma",
    street: "5th",
    street_number: "06",
  },
  {
    id: 15,
    state: "Ohio",
    state_abrev: "OH",
    city: "Dayton",
    street: "Namekagon",
    street_number: "93644",
  },
  {
    id: 16,
    state: "Florida",
    state_abrev: "FL",
    city: "Pensacola",
    street: "Linden",
    street_number: "877",
  },
  {
    id: 17,
    state: "South Carolina",
    state_abrev: "SC",
    city: "Spartanburg",
    street: "Parkside",
    street_number: "76",
  },
  {
    id: 18,
    state: "Pennsylvania",
    state_abrev: "PA",
    city: "Harrisburg",
    street: "Prairieview",
    street_number: "43",
  },
  {
    id: 19,
    state: "Indiana",
    state_abrev: "IN",
    city: "SouthBend",
    street: "Fairview",
    street_number: "76",
  },
  {
    id: 20,
    state: "Canada",
    state_abrev: "CA",
    city: "Portsmouth",
    street: "Goodland",
    street_number: "442",
  },
  {
    id: 21,
    state: "Texas",
    state_abrev: "TX",
    city: "SanAntonio",
    street: "2nd",
    street_number: "008",
  },
  {
    id: 22,
    state: "Pittsburgh",
    state_abrev: "PA",
    city: "Madison",
    street: "Banding",
    street_number: "6101",
  },
  {
    id: 23,
    state: "Arizona",
    state_abrev: "AZ",
    city: "Phoenix",
    street: "Anhalt",
    street_number: "4816",
  },
  {
    id: 24,
    state: "New York",
    state_abrev: "NY",
    city: "Buffalo",
    street: "Scott",
    street_number: "134",
  },
  {
    id: 25,
    state: "Los Angeles",
    state_abrev: "LA",
    city: "Erie",
    street: "BunkerHill",
    street_number: "36728",
  },
  {
    id: 26,
    state: "Oklahoma",
    state_abrev: "OK",
    city: "Tulsa",
    street: "Esker",
    street_number: "671",
  },
  {
    id: 27,
    state: "Georgia",
    state_abrev: "GA",
    city: "Atlanta",
    street: "Golden Leaf",
    street_number: "3",
  },
  {
    id: 28,
    state: "Pittsburgh",
    state_abrev: "PA",
    city: "Olympia",
    street: "Forest Dale",
    street_number: "94739",
  },
  {
    id: 29,
    state: "New York",
    state_abrev: "NY",
    city: "NewYorkCity",
    street: "Mayfield",
    street_number: "96968",
  },
  {
    id: 30,
    state: "California",
    state_abrev: "CA",
    city: "LosAngeles",
    street: "Portage",
    street_number: "211",
  },
];
