export const LocationDb = [
  {
    id: 1,
    state: "Pennsylvania",
    state_abrev: "PA",
    city: "Erie",
    street: "Little Fleur",
    street_number: "170",
  },
  {
    id: 2,
    state: "Michigan",
    state_abrev: "MI",
    city: "Lansing",
    street: "Ridge Oak",
    street_number: "99",
  },
  {
    id: 3,
    state: "Arizona",
    state_abrev: "AZ",
    city: "Phoenix",
    street: "Manley",
    street_number: "005",
  },
  {
    id: 4,
    state: "New York",
    state_abrev: "NY",
    city: "Brooklyn",
    street: "Nelson",
    street_number: "87369",
  },
  {
    id: 5,
    state: "South Carolina",
    state_abrev: "SC",
    city: "Columbia",
    street: "Brentwood",
    street_number: "84",
  },
  {
    id: 6,
    state: "Idaho",
    state_abrev: "ID",
    city: "Boise",
    street: "Lindbergh",
    street_number: "16",
  },
  {
    id: 7,
    state: "Florida",
    state_abrev: "FL",
    city: "PompanoBeach",
    street: "Fieldstone",
    street_number: "591",
  },
  {
    id: 8,
    state: "Texas",
    state_abrev: "TX",
    city: "San Antonio",
    street: "Dawn",
    street_number: "47",
  },
  {
    id: 9,
    state: "Washington",
    state_abrev: "WA",
    city: "Olympia",
    street: "Huxley",
    street_number: "7",
  },
  {
    id: 10,
    state: "Nevada",
    state_abrev: "NV",
    city: "CarsonCity",
    street: "Kings",
    street_number: "44462",
  },
  {
    id: 11,
    state: "Virginia",
    state_abrev: "VA",
    city: "Herndon",
    street: "Walton",
    street_number: "651",
  },
  {
    id: 12,
    state: "Texas",
    state_abrev: "TX",
    city: "ElPaso",
    street: "Fair Oaks",
    street_number: "44",
  },
  {
    id: 13,
    state: "Texas",
    state_abrev: "TX",
    city: "El Paso",
    street: "Pankratz",
    street_number: "640",
  },
  {
    id: 14,
    state: "Washington",
    state_abrev: "WA",
    city: "Tacoma",
    street: "5th",
    street_number: "06",
  },
  {
    id: 15,
    state: "Ohio",
    state_abrev: "OH",
    city: "Dayton",
    street: "Namekagon",
    street_number: "93644",
  },
  {
    id: 16,
    state: "Florida",
    state_abrev: "FL",
    city: "Pensacola",
    street: "Linden",
    street_number: "877",
  },
  {
    id: 17,
    state: "South Carolina",
    state_abrev: "SC",
    city: "Spartanburg",
    street: "Parkside",
    street_number: "76",
  },
  {
    id: 18,
    state: "Pennsylvania",
    state_abrev: "PA",
    city: "Harrisburg",
    street: "Prairieview",
    street_number: "43",
  },
  {
    id: 19,
    state: "Indiana",
    state_abrev: "IN",
    city: "SouthBend",
    street: "Fairview",
    street_number: "76",
  },
  {
    id: 20,
    state: "New Hampshire",
    state_abrev: "NH",
    city: "Portsmouth",
    street: "Goodland",
    street_number: "442",
  },
  {
    id: 21,
    state: "Texas",
    state_abrev: "TX",
    city: "SanAntonio",
    street: "2nd",
    street_number: "008",
  },
  {
    id: 22,
    state: "Wisconsin",
    state_abrev: "WI",
    city: "Madison",
    street: "Banding",
    street_number: "6101",
  },
  {
    id: 23,
    state: "Arizona",
    state_abrev: "AZ",
    city: "Phoenix",
    street: "Anhalt",
    street_number: "4816",
  },
  {
    id: 24,
    state: "New York",
    state_abrev: "NY",
    city: "Buffalo",
    street: "Scott",
    street_number: "134",
  },
  {
    id: 25,
    state: "Pennsylvania",
    state_abrev: "PA",
    city: "Erie",
    street: "BunkerHill",
    street_number: "36728",
  },
  {
    id: 26,
    state: "Oklahoma",
    state_abrev: "OK",
    city: "Tulsa",
    street: "Esker",
    street_number: "671",
  },
  {
    id: 27,
    state: "Georgia",
    state_abrev: "GA",
    city: "Atlanta",
    street: "Golden Leaf",
    street_number: "3",
  },
  {
    id: 28,
    state: "Washington",
    state_abrev: "WA",
    city: "Olympia",
    street: "Forest Dale",
    street_number: "94739",
  },
  {
    id: 29,
    state: "New York",
    state_abrev: "NY",
    city: "NewYorkCity",
    street: "Mayfield",
    street_number: "96968",
  },
  {
    id: 30,
    state: "California",
    state_abrev: "CA",
    city: "LosAngeles",
    street: "Portage",
    street_number: "211",
  },
  {
    id: 31,
    state: "Virginia",
    state_abrev: "VA",
    city: "Springfield",
    street: "Hagan",
    street_number: "8103",
  },
  {
    id: 32,
    state: "Illinois",
    state_abrev: "IL",
    city: "Chicago",
    street: "Starling",
    street_number: "1160",
  },
  {
    id: 33,
    state: "Massachusetts",
    state_abrev: "MA",
    city: "Boston",
    street: "Sachtjen",
    street_number: "67883",
  },
  {
    id: 34,
    state: "Texas",
    state_abrev: "TX",
    city: "Spring",
    street: "2nd",
    street_number: "07",
  },
  {
    id: 35,
    state: "Texas",
    state_abrev: "TX",
    city: "Amarillo",
    street: "Towne",
    street_number: "19",
  },
  {
    id: 36,
    state: "North Carolina",
    state_abrev: "NC",
    city: "Charlotte",
    street: "Browning",
    street_number: "79161",
  },
  {
    id: 37,
    state: "South Carolina",
    state_abrev: "SC",
    city: "Charleston",
    street: "3rd",
    street_number: "60174",
  },
  {
    id: 38,
    state: "Nevada",
    state_abrev: "NV",
    city: "LasVegas",
    street: "Dahle",
    street_number: "6712",
  },
  {
    id: 39,
    state: "Arizona",
    state_abrev: "AZ",
    city: "Tucson",
    street: "Kenwood",
    street_number: "6988",
  },
  {
    id: 40,
    state: "Kentucky",
    state_abrev: "KY",
    city: "Louisville",
    street: "Laurel",
    street_number: "456",
  },
  {
    id: 41,
    state: "Maryland",
    state_abrev: "MD",
    city: "Bethesda",
    street: "Talisman",
    street_number: "84158",
  },
  {
    id: 42,
    state: "Indiana",
    state_abrev: "IN",
    city: "Indianapolis",
    street: "Gateway",
    street_number: "3",
  },
  {
    id: 43,
    state: "Arizona",
    state_abrev: "AZ",
    city: "Prescott",
    street: "Veith",
    street_number: "8",
  },
  {
    id: 44,
    state: "California",
    state_abrev: "CA",
    city: "SantaMonica",
    street: "Canary",
    street_number: "333",
  },
  {
    id: 45,
    state: "Maryland",
    state_abrev: "MD",
    city: "Baltimore",
    street: "Toban",
    street_number: "8",
  },
  {
    id: 46,
    state: "South Carolina",
    state_abrev: "SC",
    city: "Beaufort",
    street: "Lakewood",
    street_number: "41",
  },
  {
    id: 47,
    state: "Ohio",
    state_abrev: "OH",
    city: "Columbus",
    street: "Parkside",
    street_number: "8",
  },
  {
    id: 48,
    state: "Louisiana",
    state_abrev: "LA",
    city: "BatonRouge",
    street: "Briar Crest",
    street_number: "6268",
  },
  {
    id: 49,
    state: "New York",
    state_abrev: "NY",
    city: "Buffalo",
    street: "Golden Leaf",
    street_number: "696",
  },
  {
    id: 50,
    state: "New York",
    state_abrev: "NY",
    city: "Buffalo",
    street: "4th",
    street_number: "69",
  },
];
