export const MenuRoute = [
  {
    id: 1,
    image: 4,
    rating: 1.9,
    name: "Bos mutus",
    type: "Campari",
    distance: 0.8,
    price: 4,
  },
  {
    id: 2,
    image: 14,
    rating: 1.4,
    name: "Cercopithecus aethiops",
    type: "Lady Fingers",
    distance: 0.9,
    price: 4,
  },
  {
    id: 3,
    image: 31,
    rating: 2.7,
    name: "Vulpes vulpes",
    type: "Dried Apple",
    distance: 0.9,
    price: 3,
  },
  {
    id: 4,
    image: 25,
    rating: 1.3,
    name: "Crotaphytus collaris",
    type: "Wine - Two Oceans Cabernet",
    distance: 0.4,
    price: 4,
  },
  {
    id: 5,
    image: 14,
    rating: 4.5,
    name: "Leipoa ocellata",
    type: "Chocolate Bar - Coffee Crisp",
    distance: 0.4,
    price: 1,
  },
  {
    id: 6,
    image: 29,
    rating: 1.2,
    name: "Bubalornis niger",
    type: "Butter Ripple - Phillips",
    distance: 0.2,
    price: 3,
  },
  {
    id: 7,
    image: 28,
    rating: 3.2,
    name: "Chlamydosaurus kingii",
    type: "Cheese - Fontina",
    distance: 0.8,
    price: 4,
  },
  {
    id: 8,
    image: 3,
    rating: 4.0,
    name: "Dasyurus maculatus",
    type: "Toamtoes 6x7 Select",
    distance: 0.4,
    price: 3,
  },
  {
    id: 9,
    image: 18,
    rating: 1.2,
    name: "Cereopsis novaehollandiae",
    type: "Chicken - Wings, Tip Off",
    distance: 0.4,
    price: 2,
  },
  {
    id: 10,
    image: 34,
    rating: 4.6,
    name: "Acrobates pygmaeus",
    type: "Cod - Black Whole Fillet",
    distance: 0.7,
    price: 4,
  },
  {
    id: 11,
    image: 11,
    rating: 1.8,
    name: "Ciconia episcopus",
    type: "Gooseberry",
    distance: 0.8,
    price: 3,
  },
  {
    id: 12,
    image: 28,
    rating: 4.2,
    name: "Dipodomys deserti",
    type: "Sausage - Meat",
    distance: 0.9,
    price: 4,
  },
  {
    id: 13,
    image: 16,
    rating: 1.9,
    name: "Macropus fuliginosus",
    type: "Triple Sec - Mcguinness",
    distance: 0.7,
    price: 4,
  },
  {
    id: 14,
    image: 5,
    rating: 4.7,
    name: "Zosterops pallidus",
    type: "Yogurt - Strawberry, 175 Gr",
    distance: 0.3,
    price: 1,
  },
  {
    id: 15,
    image: 8,
    rating: 3.2,
    name: "Colaptes campestroides",
    type: "Crab Brie In Phyllo",
    distance: 0.6,
    price: 4,
  },
  {
    id: 16,
    image: 12,
    rating: 1.6,
    name: "Larus dominicanus",
    type: "Vermouth - White, Cinzano",
    distance: 1.0,
    price: 2,
  },
  {
    id: 17,
    image: 32,
    rating: 2.5,
    name: "unavailable",
    type: "Trout - Rainbow, Frozen",
    distance: 0.2,
    price: 2,
  },
  {
    id: 18,
    image: 15,
    rating: 3.3,
    name: "Coendou prehensilis",
    type: "Energy Drink - Franks Pineapple",
    distance: 0.2,
    price: 2,
  },
  {
    id: 19,
    image: 28,
    rating: 2.9,
    name: "Bison bison",
    type: "Mushroom - Shitake, Dry",
    distance: 0.1,
    price: 3,
  },
  {
    id: 20,
    image: 31,
    rating: 2.8,
    name: "Ovibos moschatus",
    type: "Oil - Shortening - All - Purpose",
    distance: 0.4,
    price: 1,
  },
  {
    id: 21,
    image: 3,
    rating: 3.8,
    name: "Tamiasciurus hudsonicus",
    type: "Shrimp, Dried, Small / Lb",
    distance: 1.0,
    price: 4,
  },
  {
    id: 22,
    image: 23,
    rating: 3.3,
    name: "Bubulcus ibis",
    type: "Cleaner - Pine Sol",
    distance: 0.7,
    price: 2,
  },
  {
    id: 23,
    image: 15,
    rating: 4.1,
    name: "Dasyurus maculatus",
    type: "Table Cloth 144x90 White",
    distance: 0.3,
    price: 3,
  },
  {
    id: 24,
    image: 19,
    rating: 3.9,
    name: "Spheniscus magellanicus",
    type: "Tortillas - Flour, 10",
    distance: 0.4,
    price: 4,
  },
  {
    id: 25,
    image: 7,
    rating: 3.8,
    name: "Anser anser",
    type: "Cheese - Taleggio D.o.p.",
    distance: 0.7,
    price: 4,
  },
  {
    id: 26,
    image: 39,
    rating: 4.7,
    name: "Dasypus novemcinctus",
    type: "Yogurt - French Vanilla",
    distance: 1.0,
    price: 1,
  },
  {
    id: 27,
    image: 21,
    rating: 4.0,
    name: "Sterna paradisaea",
    type: "Beets - Pickled",
    distance: 0.2,
    price: 3,
  },
  {
    id: 28,
    image: 5,
    rating: 1.7,
    name: "Podargus strigoides",
    type: "Dc Hikiage Hira Huba",
    distance: 0.4,
    price: 1,
  },
  {
    id: 29,
    image: 26,
    rating: 3.1,
    name: "Grus canadensis",
    type: "Fruit Mix - Light",
    distance: 0.2,
    price: 3,
  },
  {
    id: 30,
    image: 3,
    rating: 2.1,
    name: "unavailable",
    type: "Broom - Corn",
    distance: 0.4,
    price: 3,
  },
  {
    id: 31,
    image: 12,
    rating: 3.5,
    name: "Cynomys ludovicianus",
    type: "Cotton Wet Mop 16 Oz",
    distance: 0.7,
    price: 1,
  },
  {
    id: 32,
    image: 30,
    rating: 4.9,
    name: "Eolophus roseicapillus",
    type: "Cocoa Powder - Dutched",
    distance: 0.6,
    price: 1,
  },
  {
    id: 33,
    image: 7,
    rating: 2.7,
    name: "Dendrocitta vagabunda",
    type: "Cabbage - Green",
    distance: 0.6,
    price: 4,
  },
  {
    id: 34,
    image: 5,
    rating: 2.3,
    name: "Petaurus breviceps",
    type: "Soup - Campbells Chicken",
    distance: 0.6,
    price: 2,
  },
  {
    id: 35,
    image: 10,
    rating: 1.4,
    name: "Alouatta seniculus",
    type: "Wine - Lamancha Do Crianza",
    distance: 0.7,
    price: 2,
  },
  {
    id: 36,
    image: 23,
    rating: 1.5,
    name: "Dipodomys deserti",
    type: "Chocolate - Chips Compound",
    distance: 0.3,
    price: 4,
  },
  {
    id: 37,
    image: 21,
    rating: 2.2,
    name: "Dasyurus viverrinus",
    type: "Tumeric",
    distance: 0.8,
    price: 2,
  },
  {
    id: 38,
    image: 23,
    rating: 4.5,
    name: "unavailable",
    type: "Ecolab Silver Fusion",
    distance: 0.4,
    price: 3,
  },
  {
    id: 39,
    image: 36,
    rating: 2.5,
    name: "Gabianus pacificus",
    type: "Tea - Lemon Scented",
    distance: 0.5,
    price: 1,
  },
  {
    id: 40,
    image: 11,
    rating: 2.7,
    name: "Sylvilagus floridanus",
    type: "Yoghurt Tubes",
    distance: 0.7,
    price: 4,
  },
];
